const defaultFoods = {
    breakfast: [
        "Chai + Mandazi",
        "Porridge",
        "Bread + Eggs",
        "Chapati + Beans",
        "Pancakes",
        "Yams",
        "Sweet Potatoes",
    ],
    lunch: [
        "Rice + Beans",
        "Ugali + Sukuma",
        "Pilau",
        "Githeri",
        "Rice + Beef Stew",
        "Ugali + Fish",
        "Chapati + Chicken",
        "Fries + Chips + Salad",
    ],
    supper: [
        "Ugali + Sukuma",
        "Rice + Vegetables",
        "Chapati + Stew",
        "Ugali + Beans",
        "Rice + Chicken",
        "Mukimo",
        "Ugali + Beef",
        "Pilau",
        "Githeri",
        "Ugali + Fish",
        "Rice + Beef Stew",
    ],
    fruits: [
        "Banana",
        "Mango",
        "Watermelon",
        "Pineapple",
        "Lettuce",
        "Orange",
        "Avocado",
        "Apples",
        "Fruit Salad",
    ],
};
export { defaultFoods };